version: '2'
services:
  city_displayer-app:
    image: city_displayer
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://city_displayer-postgresql:5432/city_displayer
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  city_displayer-postgresql:
    extends:
      file: postgresql.yml
      service: city_displayer-postgresql
